services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/API/API/Dockerfile
    depends_on:
      - app-db
    networks:
      - app-network
  app-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password123!"  # Strong password for app DB
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  # Expose app DB on localhost:1433
    volumes:
      - app-db-data:/var/opt/mssql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  app-db-data:
