services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/API/API/Dockerfile
    depends_on:
      - app-db
    networks:
      - app-network
    environment:
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://api.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
  app-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password123!"  # Strong password for app DB
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  # Expose app DB on localhost:1433
    volumes:
      - app-db-data:/var/opt/mssql
    networks:
      - app-network
  api.aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:13
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
    ports:
      - 18888:18888
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  app-db-data:
